Repository Kelompok-5-PPL-A/MAAMS-NG-BE, pull requests merged in 2025-03, with the labels that each got.

#29 Pbi4 subtask1
  .coveragerc
  .github/workflows/ci.yml
  .github/workflows/sonarcloud.yml
  MAAMS_NG_BE/settings.py
  MAAMS_NG_BE/urls.py
  question/__init__.py
  question/admin.py
  question/apps.py
  question/forms.py
  question/migrations/0001_initial.py
  question/migrations/0002_rename_content_problem_question.py
  question/migrations/0003_alter_problem_id.py
  question/migrations/0004_problem_status.py
  question/migrations/0005_problem_title_alter_problem_question.py
  question/migrations/0006_alter_problem_user_email.py
  question/migrations/__init__.py
  question/models.py
  question/templates/submit_question.html
  question/templates/success.html
  question/tests.py
  question/urls.py
  question/views.py
  requirements.txt
  sonar-project.properties
  tag/__init__.py
  tag/admin.py
  tag/apps.py
  tag/migrations/0001_initial.py
  tag/migrations/__init__.py
  tag/models.py
  tag/tests.py
  tag/views.py
  validator/__init__.py
  validator/constants.py
  validator/dataclasses/__init__.py
  validator/dataclasses/create_cause.py
  validator/dataclasses/create_question.py
  validator/dataclasses/field_values.py
  validator/enums.py
  validator/exceptions.py
  validator/management/commands/add_default_tags.py
  validator/models/__init__.py
  validator/models/causes.py
  validator/models/questions.py
  validator/models/tag.py
  validator/serializers.py
  validator/services/causes.py
  validator/services/questions.py
  validator/tests/__init__.py
  validator/tests/test_causes_models.py
  validator/tests/test_causes_service.py
  validator/tests/test_causes_views.py
  validator/tests/test_questions_models.py
  validator/tests/test_tag_models.py
  validator/urls.py
  validator/views/__init__.py
  validator/views/causes.py
  validator/views/questions.py
Labels: enhancement, help wanted

#34 Pbi4 subtask2
  .github/workflows/sonarcloud.yml
  validator/services/causes.py
  validator/tests/test_causes_service.py
Labels: enhancement

#37 CI/CD
  .github/workflows/ci-cd.yml
  .github/workflows/sonarcloud.yml
  .vscode/settings.json
  Dockerfile
  MAAMS_NG_BE/settings.py
  sonar-project.properties
Labels: enhancement, help wanted

#38 PBI 2, PBI 3, PBI 4 - Split Validator Folder
  MAAMS_NG_BE/settings.py
  MAAMS_NG_BE/urls.py
  cause/__init__.py
  cause/admin.py
  cause/apps.py
  cause/dataclasses/create_cause.py
  cause/migrations/0001_initial.py
  cause/migrations/0002_initial.py
  cause/migrations/__init__.py
  cause/models.py
  cause/serializers.py
  cause/services.py
  cause/tests/test_causes_models.py
  cause/tests/test_causes_services.py
  cause/tests/test_causes_views.py
  cause/urls.py
  cause/views.py
  question/dataclasses/create_question.py
  question/forms.py
  question/migrations/0002_rename_content_problem_question.py
  question/migrations/0003_alter_problem_id.py
  question/migrations/0004_problem_status.py
  question/migrations/0005_problem_title_alter_problem_question.py
  question/migrations/0006_alter_problem_user_email.py
  question/models.py
  question/serializers.py
  question/services.py
  question/templates/submit_question.html
  question/templates/success.html
  question/tests.py
  question/tests/test_question_models.py
  question/tests/test_question_services.py
  question/tests/test_question_views.py
  question/urls.py
  question/views.py
  validator/models/__init__.py
  validator/models/questions.py
  validator/models/tag.py
  validator/serializers.py
  validator/services.py
  validator/services/causes.py
  validator/services/questions.py
  validator/tests.py
  validator/tests/test_questions_service.py
  validator/tests/test_tag_models.py
  validator/urls.py
  validator/views.py
  validator/views/causes.py
  validator/views/questions.py
Labels: help wanted

#43 Authentication with Google OAuth 2.0
  .github/workflows/ci-cd.yml
  .vscode/settings.json
  MAAMS_NG_BE/settings.py
  MAAMS_NG_BE/urls.py
  authentication/__init__.py
  authentication/admin.py
  authentication/apps.py
  authentication/migrations/0001_initial.py
  authentication/migrations/0002_custom_user_migration.py
  authentication/migrations/__init__.py
  authentication/models.py
  authentication/serializers.py
  authentication/services.py
  authentication/tests/__init__.py
  authentication/tests/test_authentication_models.py
  authentication/tests/test_authentication_services.py
  authentication/tests/test_authentication_views.py
  authentication/urls.py
  authentication/views.py
  question/tests/test_question_services.py
  requirements.txt
  tag/models.py
  tag/tests.py
Labels: enhancement, help wanted
