Repository Kelompok-5-PPL-A/MAAMS-NG-BE, pull requests merged in 2025-04, with the labels that each got.

#48 Refactor Authentication System and Apply Best Practice of Programming Concept
  .vscode/settings.json
  MAAMS_NG_BE/settings.py
  MAAMS_NG_BE/urls.py
  MAAMS_NG_BE/utils.py
  apps/blacklist/migrations/0002_remove_blacklist_unique_active_blacklist_and_more.py
  apps/blacklist/migrations/0003_remove_blacklist_unique_active_blacklist_and_more.py
  apps/blacklist/models.py
  apps/blacklist/serializers.py
  apps/blacklist/services.py
  apps/blacklist/tests/__init__.py
  apps/blacklist/tests/test_blacklist_models.py
  apps/blacklist/tests/test_blacklist_services.py
  apps/blacklist/tests/test_blacklist_views.py
  apps/blacklist/urls.py
  apps/blacklist/views.py
  authentication/admin.py
  authentication/backends.py
  authentication/migrations/0004_alter_customuser_options_alter_customuser_groups_and_more.py
  authentication/migrations/0005_remove_customuser_nowa_alter_customuser_role.py
  authentication/models.py
  authentication/permissions.py
  authentication/providers/__init__.py
  authentication/providers/base.py
  authentication/providers/factory.py
  authentication/providers/google.py
  authentication/providers/sso_ui.py
  authentication/serializers.py
  authentication/services/auth.py
  authentication/services/google_auth.py
  authentication/services/interfaces.py
  authentication/services/jwt_token.py
  authentication/services/sso_ui_auth.py
  authentication/services/token.py
  authentication/tests/test_auth_models.py
  authentication/tests/test_auth_providers.py
  authentication/tests/test_auth_service.py
  authentication/tests/test_auth_views.py
  authentication/tests/test_authentication_models.py
  authentication/tests/test_authentication_services.py
  authentication/tests/test_authentication_views.py
  authentication/urls.py
  authentication/views.py
  requirements.txt
  sso_ui/config.py
  sso_ui/tests/__init__.py
  sso_ui/tests/test_sso_ui.py
  sso_ui/ticket.py
  sso_ui/token.py
Labels: enhancement, help wanted

#47 Authentication with SSO UI
  .vscode/settings.json
  MAAMS_NG_BE/settings.py
  MAAMS_NG_BE/urls.py
  MAAMS_NG_BE/utils.py
  apps/__init__.py
  apps/blacklist/__init__.py
  apps/blacklist/apps.py
  apps/blacklist/migrations/0001_initial.py
  apps/blacklist/migrations/0002_remove_blacklist_unique_active_blacklist_and_more.py
  apps/blacklist/migrations/0003_remove_blacklist_unique_active_blacklist_and_more.py
  apps/blacklist/migrations/__init__.py
  apps/blacklist/models.py
  apps/blacklist/serializers.py
  apps/blacklist/services.py
  apps/blacklist/tests/__init__.py
  apps/blacklist/tests/test_blacklist_models.py
  apps/blacklist/tests/test_blacklist_services.py
  apps/blacklist/tests/test_blacklist_views.py
  apps/blacklist/urls.py
  apps/blacklist/views.py
  authentication/admin.py
  authentication/migrations/0003_alter_customuser_options_customuser_angkatan_and_more.py
  authentication/migrations/0004_alter_customuser_options_alter_customuser_groups_and_more.py
  authentication/migrations/0005_remove_customuser_nowa_alter_customuser_role.py
  authentication/models.py
  authentication/permissions.py
  authentication/providers/__init__.py
  authentication/providers/base.py
  authentication/providers/factory.py
  authentication/providers/google.py
  authentication/providers/sso_ui.py
  authentication/serializers.py
  authentication/services.py
  authentication/services/__init__.py
  authentication/services/auth.py
  authentication/services/interfaces.py
  authentication/services/jwt_token.py
  authentication/tests/test_auth_models.py
  authentication/tests/test_auth_providers.py
  authentication/tests/test_auth_service.py
  authentication/tests/test_auth_views.py
  authentication/tests/test_authentication_models.py
  authentication/tests/test_authentication_services.py
  authentication/tests/test_authentication_views.py
  authentication/urls.py
  authentication/views.py
  requirements.txt
  sso_ui/__init__.py
  sso_ui/apps.py
  sso_ui/config.py
  sso_ui/migrations/__init__.py
  sso_ui/tests/__init__.py
  sso_ui/tests/test_sso_ui.py
  sso_ui/ticket.py
  sso_ui/token.py
Labels: enhancement, help wanted

#52 PBI 2 - Update Question App
  apps/blacklist/tests/test_blacklist_services.py
  question/migrations/0002_question_user.py
  question/models.py
  question/serializers.py
  question/services.py
  question/tests/test_question_models.py
  question/tests/test_question_services.py
  question/tests/test_question_views.py
  question/urls.py
  question/views.py
Labels: help wanted, question

#63 PBI 3 Add Causes & PBI 4 Validation Causes
  .github/workflows/ci-cd.yml
  MAAMS_NG_BE/settings.py
  apps/blacklist/migrations/0006_remove_blacklist_unique_active_blacklist_and_more.py
  apps/blacklist/migrations/0007_remove_blacklist_unique_active_blacklist_and_more.py
  authentication/migrations/0002_custom_user_migration.py
  cause/migrations/0005_alter_causes_cause.py
  cause/models.py
  validator/services.py
  validator/tests/test_validator_rate_limiter.py
  validator/tests/test_validator_services.py
  validator/utils/__init__.py
  validator/utils/rate_limiter.py
  validator/views.py
Labels: enhancement
